### ISSUE TITLE
vcClock shows only 2 of the 3 decimals, 3rd is always 0

### ISSUE THREAD

**Issue by fractalgee** [catronomix/catro-modulo#26]
If I set the vcClock 6.667 (tooltip shows it set correctly), the vcClock shows 6.660 if snap is all the way to the left, snap in middle it shows 6.000. In any case, why the 3rd decimal always 0? Wasted decimal place in display, please fix so no confusion arises what it is really set to

**Comment by catronomix** [comment]
the display has a numerical resolution of 2 decimals, but since the integer part can have more than one digit and the decimal point can shift, the display is zero-padded because 0.000 looks better than 00.00
And since nobody dances to single-digit bpms let alone feel a 0.01 bpm difference I didn't consider it necessary.

There is however a bug in the way the values are rounded, causing the clock to output at input values but the CV signal to output at rounded values in some cases. That is something I might one day address.
